language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - pip install "Django>=$DJANGO,<${DJANGO}.99" requests twilio==3.6.6 mock

script:
- "`which django-admin.py` test sms_engine --settings=sms_engine.test_settings --pythonpath=."
